### ISSUE TITLE
Request for Feature: Total Count of Tests per Suite on EVENT_SUITE_BEGIN

### ISSUE THREAD

**Issue by gdavidkov** [kraenhansen/mocha-remote#95]
Hi,

I'm reaching out to request a new feature in the testing framework. Currently, during the EVENT_SUITE_BEGIN event, I'm unable to determine the total count of tests per suite. Having this information would greatly enhance the flexibility and functionality of the framework for users like myself.

Thank you for your attention to this matter.

Sincerely,
Georgi Davidkov

**Comment by kraenhansen** [comment]
Just to be sure, are you looking to get this information on the client or the server?
